### PR TITLE
Changes for work with new API of swiftmailer

### PR DESCRIPTION
**Pull request by demenkov**
Changes for https://github.com/swiftmailer/swiftmailer/commit/5a0199b1ac8409791086098557da53b1cc92fc04

### CODE REVIEW

**Comment by cebe** [comment]
is this backwards compatible?

**Comment by demenkov** [comment]
No.
But when I'm runing composer update, I get new version of swiftmailer and it breaks mailer in Yii.

**Comment by demenkov** [comment]
Currently I fixed it with adding
```javascript
"swiftmailer/swiftmailer": "dev-master#db95cfa68a8bc91d1c54f75c416f481c9a8bd100"
```
in application composer.json

**Comment by cebe** [comment]
we should adjust version constraints in composer.json then.

**Comment by demenkov** [comment]
How about to lock on 5.4.0 version? 
https://github.com/swiftmailer/swiftmailer/releases/tag/v5.4.0
```javascript
"swiftmailer/swiftmailer": "5.4.0"
```
Create new request or modify this?

**Comment by klimov-paul** [comment]
Resolved by commit cab046b

**Pull request closed without merging**
